version: '3.8'
services:
  product:
    build: ./microservices/product
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=production
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:5044"
        tag: "product"

  order:
    build: ./microservices/order
    ports:
      - "8004:8004"
    environment:
      - NODE_ENV=production
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:5044"
        tag: "order"

  cart:
    build: ./microservices/cart
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=production
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:5044"
        tag: "cart"

  auth:
    build: ./microservices/auth
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:5044"
        tag: "auth"

  elk:
    container_name: elk
    build: ./elk
    ports:
      - "9200:9200"
      - "5044:5044"
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
