# Dockerfile
# Use Node.js official image
FROM node:14-alpine

# Create and set the app directory
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the application's port (specify unique port per service)
EXPOSE 8003

# Start the application
CMD ["node", "app.js"]
